version: '3.8'
services:
  tiktok-recorder:
    build:
      context: ./recorder
      dockerfile: Dockerfile
      args:
        COOKIE: ${TIKTOK_COOKIE}
        TIMEZONE: ${TIMEZONE-:Etc/UTC}
    restart: always
    volumes:
      - ./videos:/app/src/videos
    environment:
      - TIMEZONE=${TIMEZONE-:Etc/UTC}
      - USER=${TIKTOK_USER}
      - COOKIE=${TIKTOK_COOKIE}

  uploader:
    entrypoint: ["./upload.sh"]
    build:
      context: ./rclone
      dockerfile: Dockerfile
      args:
        RCLONE_CONFIG_TYPE: sftp
        RCLONE_CONFIG_HOST: ${SFTP_HOST}
        RCLONE_CONFIG_USER: ${SFTP_USER}
        RCLONE_CONFIG_PASS: ${SFTP_PASS}
        RCLONE_CONFIG_PORT: ${SFTP_PORT-:22}
        REMOTE_PATH: ${SFTP_REMOTE_PATH}
    volumes:
      - ./videos:/app/videos
    environment:
      - RCLONE_CONFIG_TYPE=sftp
      - RCLONE_CONFIG_HOST=${SFTP_HOST}
      - RCLONE_CONFIG_USER=${SFTP_USER}
      - RCLONE_CONFIG_PASS=${SFTP_PASS}
      - RCLONE_CONFIG_PORT=${SFTP_PORT-:22}
      - REMOTE_PATH=${SFTP_REMOTE_PATH}
    restart: always
    depends_on:
      - tiktok-recorder
